### ISSUE TITLE
In part03, expectElementsWithThenComplete

### ISSUE THREAD

**Issue by Dyrcj** [reactor/lite-rx-api-hands-on#29]
In my test code, I checked User with expectNext.
Like the following:
```java
void expectSkylerJesseComplete(Flux<User> flux) {
		StepVerifier.create(flux).expectNext(new User("swhite", null, null),
				new User("jpinkman", null, null))
				.expectComplete().verify();
		//fail();
	}
```
But I got an error:
```java
java.lang.AssertionError: expectation failed (failed running expectation on signal [onNext(Person{username='swhite', firstname='null', lastname='null'})] with [java.lang.NullPointerException]:
)

	at reactor.test.DefaultStepVerifierBuilder.failPrefix(DefaultStepVerifierBuilder.java:1679)
	at reactor.test.DefaultStepVerifierBuilder.fail(DefaultStepVerifierBuilder.java:1675)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onExpectation(DefaultStepVerifierBuilder.java:1017)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onNext(DefaultStepVerifierBuilder.java:764)
	at reactor.core.publisher.FluxArray$ArraySubscription.fastPath(FluxArray.java:164)
	at reactor.core.publisher.FluxArray$ArraySubscription.request(FluxArray.java:90)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onSubscribe(DefaultStepVerifierBuilder.java:781)
	at reactor.core.publisher.FluxArray.subscribe(FluxArray.java:55)
	at reactor.core.publisher.FluxArray.subscribe(FluxArray.java:61)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:532)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:508)
	at io.pivotal.literx.Part03StepVerifier.expectSkylerJesseComplete(Part03StepVerifier.java:74)
	at io.pivotal.literx.Part03StepVerifier.expectElementsWithThenComplete(Part03StepVerifier.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
why `expectNext("foo", "bar") ` in `expect2ElementsThenError` is alright?

**Comment by simonbasle** [comment]
That's because of the `User#equals` method, you are testing for equality with an incomplete `User` object with a `null` firstname and lastname, so it throws an NPE. Look at how the solution uses a predicate on the username getter. On the other hand, with `expectNext("foo", "bar")` you are dealing with plain strings...
